/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolFunction_8 (
    input [15:0] a,
    input [15:0] b,
    input [3:0] alufnbooler,
    output reg [15:0] res
  );
  
  
  
  integer i;
  
  integer input_bits;
  
  always @* begin
    for (i = 1'h0; i < 5'h10; i = i + 1) begin
      input_bits = {a[(i)*1+0-:1], b[(i)*1+0-:1]};
      
      case (input_bits)
        2'h0: begin
          res[(i)*1+0-:1] = alufnbooler[0+0-:1];
        end
        2'h2: begin
          res[(i)*1+0-:1] = alufnbooler[1+0-:1];
        end
        2'h1: begin
          res[(i)*1+0-:1] = alufnbooler[2+0-:1];
        end
        2'h3: begin
          res[(i)*1+0-:1] = alufnbooler[3+0-:1];
        end
        default: begin
          res[(i)*1+0-:1] = 1'h0;
        end
      endcase
    end
  end
endmodule
