/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module cmpFunction_9 (
    input z,
    input v,
    input n,
    input [1:0] alufncmper,
    output reg [15:0] res
  );
  
  
  
  reg temp;
  
  always @* begin
    
    case (alufncmper)
      2'h1: begin
        temp = z;
      end
      2'h2: begin
        temp = n ^ v;
      end
      2'h3: begin
        temp = z | (n ^ v);
      end
      default: begin
        temp = 1'h0;
      end
    endcase
    res[0+0-:1] = temp;
    res[1+14-:15] = 15'h0000;
  end
endmodule
