/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifterFunction_10 (
    input [15:0] a,
    input [15:0] b,
    input [1:0] alufnshifter,
    output reg [15:0] res
  );
  
  
  
  always @* begin
    
    case (alufnshifter)
      2'h0: begin
        res = a << b[0+3-:4];
      end
      2'h1: begin
        res = a >> b[0+3-:4];
      end
      2'h3: begin
        res = $signed(a) >>> b[0+3-:4];
      end
      default: begin
        res = a;
      end
    endcase
  end
endmodule
